# Generated by Django 3.0.5 on 2020-06-13 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.FileField(upload_to='FoodImage', verbose_name='Composition')),
                ('composition', models.TextField(verbose_name='Composition')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restoran.Category', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Zakaz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('date', models.DateField(verbose_name='Date')),
                ('number', models.IntegerField(verbose_name='Number')),
                ('table', models.CharField(choices=[('t1', 'Table 1'), ('t2', 'Table 2'), ('t3', 'Table 3'), ('t4', 'Table 4'), ('t5', 'Table 5'), ('t6', 'Table 6')], default='t1', max_length=2, verbose_name='Table')),
                ('foods', models.ManyToManyField(to='restoran.Food')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
