# Generated by Django 3.0.5 on 2020-06-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restoran', '0002_auto_20200613_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zakaz',
            name='table',
            field=models.CharField(choices=[('Table 1', 'Table 1'), ('Table 2', 'Table 2'), ('Table 3', 'Table 3'), ('Table 4', 'Table 4'), ('Table 5', 'Table 5'), ('Table 6', 'Table 6')], default='Table 1', max_length=7, verbose_name='Table'),
        ),
    ]
